version: '3'

services:
  product-service:
    container_name: product-service
    restart: always
    build: ./product
    volumes:
      - ./product:/usr/src/app/
    ports:
      - 5001:80
    depends_on:
      - database-service
  database-service:
    container_name: database-service
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=testdb
      - PGDATA=/tmp
    volumes:
      - .$HOME/docker/volumes/postgres2:/var/lib/postgresql/data
    ports:
      - 5002:5432
